export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const ADD_VIDEO = 'ADD_VIDEO';
export const ADD_VIDEO_SUCCESS = 'ADD_VIDEO_SUCCESS';
export const ADD_VIDEO_FAILURE = 'ADD_VIDEO_FAILURE';

export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const REMOVE_VIDEO_SUCCESS = 'REMOVE_VIDEO_SUCCESS';
export const REMOVE_VIDEO_FAILURE = 'REMOVE_VIDEO_FAILURE';

export const UPDATE_VIDEO_CORE_INSIGHT = 'UPDATE_VIDEO_CORE_INSIGHT';
export const UPDATE_VIDEO_CORE_INSIGHT_SUCCESS = 'UPDATE_VIDEO_CORE_INSIGHT_SUCCESS';
export const UPDATE_VIDEO_CORE_INSIGHT_FAILURE = 'UPDATE_VIDEO_CORE_INSIGHT_FAILURE';

export const UPDATE_VIDEO_TAGS = 'UPDATE_VIDEO_TAGS';
export const UPDATE_VIDEO_TAGS_SUCCESS = 'UPDATE_VIDEO_TAGS_SUCCESS';
export const UPDATE_VIDEO_TAGS_FAILURE = 'UPDATE_VIDEO_TAGS_FAILURE';

export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAILURE = 'GET_PLAYLISTS_FAILURE';

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILURE = 'CREATE_PLAYLIST_FAILURE';

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAILURE = 'DELETE_PLAYLIST_FAILURE';

export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_FAILURE = 'UPDATE_PLAYLIST_FAILURE';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE';

export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';

export const DELETE_TAG = 'DELETE_TAG';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
